### ISSUE TITLE
scope lapack-based module

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/multitemporal#31]
@naterubin scope out calling lapack from module (maybe from cython module)

**Comment by bziniti** [comment]
it's _relatively_ easy to deal with: https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.isfortran.html
it has to do with the way that fortran arrays need to be aligned
you can make sure the numpy arrays are correct by creating them like this: `np.array([1,2,3], order='FORTRAN')`
and you can check that arrays passed into a function are aligned correctly by checking `ary.flags.f_contiguous`

**Comment by bziniti** [comment]
recommendation is to use the functions in `scipy.linalg` as these are using blas and lapack under the hood
